# Generated by Django 6.0 on 2025-12-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Professionell städning i Stockholm", max_length=255
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="Vi levererar skinande rena resultat för både privatpersoner och företag."
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="hero/"),
                ),
                (
                    "hero_cta_text",
                    models.CharField(default="Begär offert", max_length=50),
                ),
                (
                    "hero_cta_link",
                    models.CharField(default="/begar-offert/", max_length=255),
                ),
                (
                    "about_snippet_title",
                    models.CharField(default="Om Oss", max_length=255),
                ),
                (
                    "about_snippet_text",
                    models.TextField(
                        default="GRB Servicebyrå AB grundades 2017 och vi har sedan dess levererat städtjänster med högsta kvalitet."
                    ),
                ),
                (
                    "about_image",
                    models.ImageField(blank=True, null=True, upload_to="about/"),
                ),
            ],
            options={
                "verbose_name": "Home Page Content",
            },
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="GRB Servicebyrå AB", max_length=255),
                ),
                ("phone", models.CharField(default="072 030 05 66", max_length=50)),
                ("email", models.EmailField(default="info@grbs.se", max_length=254)),
                (
                    "address",
                    models.TextField(
                        default="Gustav III:s Boulevard 16\nSE 16972 SOLNA"
                    ),
                ),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Site Configuration",
            },
        ),
    ]
