# Generated by Django 6.0 on 2025-12-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Namn')),
                ('email', models.EmailField(max_length=254, verbose_name='E-post')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=255, verbose_name='Ämne')),
                ('message', models.TextField(verbose_name='Meddelande')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Namn')),
                ('email', models.EmailField(max_length=254, verbose_name='E-post')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('service_type', models.CharField(max_length=255, verbose_name='Typ av tjänst')),
                ('message', models.TextField(verbose_name='Meddelande')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
