# Generated by Django 5.2.6 on 2026-01-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_pricingpackage_service_benefits_service_features_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingpackage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
